import type { Metadata } from "next";
import { Geist_Mono, Noto_Sans_SC } from "next/font/google";
import "./globals.css";
import { AppProviders } from "./providers";
import Head from "next/head";

const geistMono = Geist_Mono({
  variable: "--font-en",
  subsets: ["latin"],
});

const notoSansSc = Noto_Sans_SC({
  variable: "--font-cn",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh" suppressHydrationWarning>
      <Head>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
      </Head>
      <body
        className={`${notoSansSc.variable} ${geistMono.variable} antialiased duration-200`}
      >
        <AppProviders>
          { children }
        </AppProviders>
      </body>
    </html>
  );
}
